Repository secureCodeBox/defectdojo-client-java, pull requests merged in 2023-07, with the labels that each got.

#45 Enable dependabot
  .github/dependabot.yml
Labels: bug

#52 Improve sonatype publishing
  build.gradle
Labels: enhancement

#54 Add myself as developer
  build.gradle
Labels: documentation

#50 #23 Add failing tests to reproduce broken equals implementation
  build.gradle
  src/test/java/io/securecodebox/persistence/defectdojo/model/EndpointTest.java
  src/test/java/io/securecodebox/persistence/defectdojo/model/EngagementTest.java
  src/test/java/io/securecodebox/persistence/defectdojo/model/FindingTest.java
  src/test/java/io/securecodebox/persistence/defectdojo/model/GroupMemberTest.java
  src/test/java/io/securecodebox/persistence/defectdojo/model/GroupTest.java
  src/test/java/io/securecodebox/persistence/defectdojo/model/ProductGroupTest.java
  src/test/java/io/securecodebox/persistence/defectdojo/model/ProductTest.java
  src/test/java/io/securecodebox/persistence/defectdojo/model/ProductTypeTest.java
  src/test/java/io/securecodebox/persistence/defectdojo/model/ResponseTest.java
  src/test/java/io/securecodebox/persistence/defectdojo/model/RiskAcceptanceTest.java
  src/test/java/io/securecodebox/persistence/defectdojo/model/ScanFileTest.java
  src/test/java/io/securecodebox/persistence/defectdojo/model/TestTest.java
  src/test/java/io/securecodebox/persistence/defectdojo/model/TestTypeTest.java
  src/test/java/io/securecodebox/persistence/defectdojo/model/ToolConfigTest.java
  src/test/java/io/securecodebox/persistence/defectdojo/model/ToolTypeTest.java
  src/test/java/io/securecodebox/persistence/defectdojo/model/UserProfileTest.java
  src/test/java/io/securecodebox/persistence/defectdojo/model/UserTest.java
Labels: bug

#56 Add myself as developer
  build.gradle
Labels: documentation

#58 Update and fix workflows
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: enhancement

#53 #35 First parts of documentation for release ceremony
  release.md
Labels: documentation

#62 35 release documentation
  docs/release.md
  docs/release_staging_1.png
  docs/release_staging_2.png
  docs/release_staging_3.png
  docs/release_staging_4.png
Labels: documentation

#63 Update issue templates
  .github/ISSUE_TEMPLATE/--feature-request.md
  .github/ISSUE_TEMPLATE/🐞-bug-report.md
  .github/ISSUE_TEMPLATE/📚-documentation-issue.md
  .github/ISSUE_TEMPLATE/🤨-question.md
Labels: enhancement

#66 Remove subkey from release documentation
  docs/release.md
Labels: documentation

#61 Use fixed Ubuntu version in actions instead of latest
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: enhancement

#65 Create SECURITY.md
  SECURITY.md
Labels: documentation, enhancement

#68 Enable Dependabot for Workflow updates
  .github/dependabot.yml
Labels: dependencies
