Repository secureCodeBox/defectdojo-client-java, pull requests merged in 2023-08, with the labels that each got.

#72 #35 Add dependency information to readme
  README.md
Labels: documentation

#74 Fix github actions output variable name
  .github/workflows/release.yml
Labels: bug

#82 Remove maven wrapper
  .github/workflows/release.yml
Labels: bug

#83 Add bot token already in checkout
  .github/workflows/release.yml
Labels: bug

#84 Revert "Add bot token already in checkout"
  .github/workflows/release.yml
Labels: bug

#87 Automatically update versions in README.md upon release
  .github/workflows/release.yml
Labels: enhancement

#89 Fix release workflow with new permissions
  .github/workflows/release.yml
Labels: bug

#90 Adjust README version to 1.0.1
  README.md
Labels: documentation
