Repository secureCodeBox/defectdojo-client-java, pull requests merged in 2024-01, with the labels that each got.

#100 Updated all DD scanTypes to v2.29 due to a lot more parser integrated already
  src/main/java/io/securecodebox/persistence/defectdojo/ScanType.java
Labels: enhancement, java

#109 Use latest 5.x Spring dependency
  pom.xml
Labels: dependencies

#116 Add Ignore File for Git Blame
  .git-blame-ignore-revs
Labels: enhancement
